const empresas = [
    {
        id: 1,
        nome: "Empresa 1",
        category: "Restaurante",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "(11) 99999-9999",
        endereco: "Rua A, 123",
        status: "Aberta Agora", // ou "Fechada" ou "Fecha em 5 min"
        imagem: "placeholder.png",
        detalhes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae elit libero, a pharetra augue. Maecenas sed diam eget risus varius blandit sit amet non magna.",
        site: "https://www.empresa1.com.br"
    },
    {
        id: 2,
        nome: "Empresa 2",
        categoria: "Mercado",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "(11) 99999-9999",
        endereco: "Rua B, 456",
        status: "Fechada",
        imagem: "placeholder.png",
        detalhes: "Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Cras mattis consectetur purus sit amet fermentum.",
        site: "https://www.empresa2.com.br"
    },
    {
        id: 3,
        nome: "Empresa 3",
        categoria: "Restaurante",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "(11) 99999-9999",
        endereco: "Rua c, 789",
        status: "Fecha em 5 min",
        imagem: "placeholder.png",
        detalhes: "Aenean lacinia bibendum nulla sed consectetur. Nullam id dolor id nibh ultricies vehicula ut id elit.",
        site: "https://www.empresa3.com.br"
    },
    {
        id: 4,
        nome: "Empresa 4",
        categoria: "Farmácia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "(11) 99999-9999",
        endereco: "Rua d, 1011",
        status: "Aberta Agora",
        imagem: "img/empresa4.png",
        detalhes: "Curabitur blandit tempus porttitor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. ",
        site: "https://www.empresa4.com.br"
    },
    {
        id: 5,
        nome: "Empresa 5",
        categoria: "Supermercado",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "(11) 99999-9999",
        endereco: "Rua d, 1011",
        status: "Aberta Agora",
        imagem: "img/empresa5.png",
        detalhes: "Curabitur blandit tempus porttitor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. ",
        site: "https://www.empresa4.com.br"
    }, {
        id: 6,
        nome: "Empresa 6",
        categoria: "Barbearia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "(11) 99999-9999",
        endereco: "Rua d, 1011",
        status: "Aberta Agora",
        imagem: "img/empresa6.png",
        detalhes: "Curabitur blandit tempus porttitor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. ",
        site: "https://www.empresa4.com.br"
    }, {
        id: 7,
        nome: "Empresa 7",
        categoria: "Academia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "(11) 99999-9999",
        endereco: "Rua d, 1011",
        status: "Aberta Agora",
        imagem: "img/empresa7.png",
        detalhes: "Curabitur blandit tempus porttitor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. ",
        site: "https://www.empresa4.com.br"
    }, {
        id: 8,
        nome: "Empresa 8",
        categoria: "Farmácia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "(11) 99999-9999",
        endereco: "Rua d, 1011",
        status: "Aberta Agora",
        imagem: "img/empresa8.png",
        detalhes: "Curabitur blandit tempus porttitor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. ",
        site: "https://www.empresa4.com.br"
    }, {
        id: 9,
        nome: "Empresa 9",
        categoria: "Farmácia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "(11) 99999-9999",
        endereco: "Rua d, 1011",
        status: "Aberta Agora",
        imagem: "img/empresa9.png",
        detalhes: "Curabitur blandit tempus porttitor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. ",
        site: "https://www.empresa4.com.br"
    }, {
        id: 10,
        nome: "Empresa 10",
        categoria: "Farmácia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "(11) 99999-9999",
        endereco: "Rua d, 1011",
        status: "Aberta Agora",
        imagem: "img/empresa10.png",
        detalhes: "Curabitur blandit tempus porttitor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. ",
        site: "https://www.empresa4.com.br"
    }, {
        id: 11,
        nome: "Empresa 4",
        categoria: "Farmácia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "(11) 99999-9999",
        endereco: "Rua d, 1011",
        status: "Aberta Agora",
        imagem: "img/empresa11.png",
        detalhes: "Curabitur blandit tempus porttitor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. ",
        site: "https://www.empresa4.com.br"
    },
];