 const empresasData = [
    {
        id: 1,
        nome: "Empresa 1",
        categoria: "Restaurante",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "11999999999",
        endereco: "Av. Paulista, 1000, São Paulo",
        status: "Aberta Agora",
        imagem: "img/empresa1.png",
        detalhes: "Lorem ipsum dolor sit amet...",
        site: "https://www.empresa1.com.br",
        lat: -23.561684,
        lng: -46.656169 // Coordenadas da Av. Paulista, 1000 (aproximado)
    },
    {
        id: 2,
        nome: "Empresa 2",
        categoria: "Mercado",
        descricao: "Descrição da empresa",
        telefone: "(11) 88888-8888",
        whatsapp: "11888888888",
        endereco: "Rua Augusta, 200, São Paulo",
        status: "Fechada",
        imagem: "img/empresa2.png",
        detalhes: "Fusce dapibus, tellus ac cursus commodo...",
        site: "https://www.empresa2.com.br",
        lat: -23.543418,
        lng: -46.644822 // Coordenadas da Rua Augusta, 200 (aproximado)
    },
    {
        id: 3,
        nome: "Empresa 3",
        categoria: "Restaurante",
        descricao: "Descrição da empresa",
        telefone: "(11) 77777-7777",
        whatsapp: "11777777777",
        endereco: "Rua da Consolação, 500, São Paulo",
        status: "Fecha em 5 min",
        imagem: "img/empresa3.png",
        detalhes: "Aenean lacinia bibendum nulla sed consectetur...",
        site: "https://www.empresa3.com.br",
        lat: -23.547643,
        lng: -46.654328 // Coordenadas da Rua da Consolação, 500 (aproximado)
    },
    {
        id: 4,
        nome: "Empresa 4",
        categoria: "Farmácia",
        descricao: "Descrição da empresa",
        telefone: "(11) 66666-6666",
        whatsapp: "11666666666",
        endereco: "Av. Brigadeiro Faria Lima, 1500, São Paulo",
        status: "Aberta Agora",
        imagem: "img/empresa4.png",
        detalhes: "Curabitur blandit tempus porttitor...",
        site: "https://www.empresa4.com.br",
        lat: -23.573441,
        lng: -46.675387 // Coordenadas da Av. Brigadeiro Faria Lima, 1500 (aproximado)
    },
     {
        id: 5,
        nome: "Empresa 5",
        categoria: "Supermercado",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "11999999999",
        endereco: "Av. Rebouças, 2000, São Paulo",
        status: "Aberta Agora",
        imagem: "img/empresa5.png",
        detalhes: "Curabitur blandit tempus porttitor...",
        site: "https://www.empresa5.com.br",
        lat: -23.564987,
        lng: -46.665412 // Coordenadas da Av. Rebouças, 2000 (aproximado)
    }, {
        id: 6,
        nome: "Empresa 6",
        categoria: "Barbearia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "11999999999",
        endereco: "Rua Haddock Lobo, 300, São Paulo",
        status: "Aberta Agora",
        imagem: "img/empresa6.png",
        detalhes: "Curabitur blandit tempus porttitor...",
        site: "https://www.empresa6.com.br",
        lat: -23.559148,
        lng: -46.664032 // Coordenadas da Rua Haddock Lobo, 300 (aproximado)
    }, {
        id: 7,
        nome: "Empresa 7",
        categoria: "Academia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "11999999999",
        endereco: "Rua Oscar Freire, 500, São Paulo",
        status: "Aberta Agora",
        imagem: "img/empresa7.png",
        detalhes: "Curabitur blandit tempus porttitor...",
        site: "https://www.empresa7.com.br",
        lat: -23.566132,
        lng: -46.670030 // Coordenadas da Rua Oscar Freire, 500 (aproximado)
    }, {
        id: 8,
        nome: "Empresa 8",
        categoria: "Farmácia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "11999999999",
        endereco: "Av. Brasil, 1000, São Paulo",
        status: "Aberta Agora",
        imagem: "img/empresa8.png",
        detalhes: "Curabitur blandit tempus porttitor...",
        site: "https://www.empresa8.com.br",
        lat: -23.561828,
        lng: -46.658230 // Coordenadas da Av. Brasil, 1000 (aproximado)
    }, {
        id: 9,
        nome: "Empresa 9",
        categoria: "Farmácia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "11999999999",
        endereco: "Rua Estados Unidos, 1500, São Paulo",
        status: "Aberta Agora",
        imagem: "img/empresa9.png",
        detalhes: "Curabitur blandit tempus porttitor...",
        site: "https://www.empresa9.com.br",
        lat: -23.565139,
        lng: -46.673569 // Coordenadas da Rua Estados Unidos, 1500 (aproximado)
    }, {
        id: 10,
        nome: "Empresa 10",
        categoria: "Farmácia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "11999999999",
        endereco: "Av. Cidade Jardim, 500, São Paulo",
        status: "Aberta Agora",
        imagem: "img/empresa10.png",
        detalhes: "Curabitur blandit tempus porttitor...",
        site: "https://www.empresa10.com.br",
        lat: -23.570192,
        lng: -46.678855 // Coordenadas da Av. Cidade Jardim, 500 (aproximado)
    }, {
        id: 11,
        nome: "Empresa 11",
        categoria: "Farmácia",
        descricao: "Descrição da empresa",
        telefone: "(11) 99999-9999",
        whatsapp: "11999999999",
        endereco: "Av. Europa, 100, São Paulo",
        status: "Aberta Agora",
        imagem: "img/empresa11.png",
        detalhes: "Curabitur blandit tempus porttitor...",
        site: "https://www.empresa11.com.br",
        lat: -23.573749,
        lng: -46.679882 // Coordenadas da Av. Europa, 100 (aproximado)
    },
];

// --- END OF FILE data.js ---
